Adds make rule for building the rpm.
hmhco/vault-gatekeeper-mesos pull request #3
Opened 2018-10-05 23:44 UTC by ilapost

### Reason
Gatekeeper needs to be installed in core.
### Implementation
Added rules in Makefile
### Verification
Run make
### Testing
Created successfully the rpm.

2018-10-11 13:43 UTC, kytomaki requested changes
Generally looks good. Just minor nitpicking. In general I think we should get rid of bedrock dependant internal stuff on a public repo.

Also the fpm command could use maybe a `--prefix /usr/local/bin` or similar so that the gatekeeper binary wouldn't get installed on `/`

We might want to include a config file template in `/etc` provided that the gatekeeper needs one? That way the operating system will know what files belong to which package.

The commit messages could be in an imperative as they seem to be on the upstream repo.  Also some of them might be rebased maybe?

2018-10-11 13:43 UTC, kytomaki commented on Makefile
> +	$(DOCKER) docker.br.hmheng.io/hmheng-infra/gatekeeper-build:v1.0.3-10-ga65b145 make -C /go/src/github.com/nemosupremo/vault-gatekeeper -f Makefile.docker $@
I don't think we should use internal docker repositories in a public repo.

2018-10-11 13:43 UTC, kytomaki commented on Makefile
> +all: $(RPM)
We might want to have a different `.PHONY` target for generating the rpm. e.g. `rpm`. The first (`all`) target for generating the binary could be left as is.

2018-10-11 13:43 UTC, kytomaki commented on Makefile
> +	$(DOCKER) docker.br.hmheng.io/hmheng-infra/fpm:latest make -C /go/src/github.com/nemosupremo/vault-gatekeeper -f Makefile.docker $@
There's the internal repo again. Also we might want to simplify the build with a multistage-build?

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +$(RPM):
`$(RPM)` target could depend on `$(GATEKEEPER)`

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +	mkdir -p dist/package
We could get rid of this ...

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +	install $(GATEKEEPER) dist/package
... and get rid of this, if ...

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +	  -C dist/package \
... we get of rid of this also and ...

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +	  .
... replace this with `$(GATEKEEPER)`

2018-10-11 13:43 UTC, kytomaki commented on common.mk
> +RPM := $(RPM_NAME)-$(VERSION)-$(ITERATION).x86-64.rpm
Architecture should be `x86_64` with an underscore

2018-10-11 13:43 UTC, kytomaki commented on Makefile
> +$(RPM): $(GATEKEEPER)
I think this should be `dist/$(RPM)`

2018-10-11 13:43 UTC, kytomaki commented on Makefile.docker
> +$(RPM):
And also be rewritten as `dist/$(RPM)`

2018-10-11 14:15 UTC, vaine commented
re: `/usr/local/bin`

That should be `/usr/bin`. That's how all other RPMs in bedrock do it.

2018-10-11 14:15 UTC, jaakkoo commented
Do not listen to that bearded bsd -guy about the binary location. Binaries installed via package manager should be installed to `/usr/bin`

2018-10-11 15:22 UTC, ilapost commented on Makefile
> +	$(DOCKER) docker.br.hmheng.io/hmheng-infra/gatekeeper-build:v1.0.3-10-ga65b145 make -C /go/src/github.com/nemosupremo/vault-gatekeeper -f Makefile.docker $@
These changes are all featured in the new bedrock branch whose purpose is to build the rpm. I can try to get rid of the gatekeeper-build image, but the purpose of this branch is still for internal consumption. I am not sure if these changes are useful to the original repo and it was never my intent to publish them. I have committed changes in Gatekeeper itself straight to the master branch with the intent of maybe someday merge them but this is just for bedrock.

2018-10-15 15:14 UTC, kytomaki commented
So at least install the binary in `/usr/bin`. The target dependancies are mostly polish. They allow make to determine if binaries are already built.

You could `install` the `$(GATEKEEPER) into `dist/packages/usr/bin` and then use the `-C` flag of fpm or use the `--prefix` to determine the same thing. Currently the rpm installs the binary into `/` which is quite unacceptable.

If you create the `dist(packages(...` hierachy we could also include `dist/package/etc/gatekeeper.conf` or similar it they exist.

2018-11-01 21:27 UTC, closed without merging